[project]
name = 'glamora'
description = 'A decentralized fashion social platform with STX tipping and secure storage'
authors = ['Timothy Terese Chimbiv']
telemetry = true
cache_dir = '.\.cache'
requirements = []

[contracts.sip-009]
path = 'contracts/sip-009.clar'
clarity_version = 4
epoch = '3.3'

[contracts.sbtc-token]
path = 'contracts/sbtc-token.clar'
clarity_version = 1
epoch = '2.05'

[contracts.usdcx-token]
path = 'contracts/usdcx-token.clar'
clarity_version = 4
epoch = '3.3'

[contracts.storage-v3]
path = 'contracts/storage-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.bridge-adapter]
path = 'contracts/bridge-adapter.clar'
clarity_version = 4
epoch = '3.3'

[contracts.glamora-nft-v2]
path = 'contracts/glamora-nft.clar'
clarity_version = 4
epoch = '3.3'

[contracts.main]
path = 'contracts/main.clar'
clarity_version = 4
epoch = '3.3'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
