[project]
name = 'glamora'
description = 'A decentralized fashion social platform with STX tipping and secure storage'
authors = ['Timothy Terese Chimbiv']
telemetry = true
cache_dir = '.\.cache'
requirements = []

[contracts.sbtc-token]
path = "contracts/sbtc-token.clar"
clarity_version = 1
epoch = 2.05

[contracts.glamora-nft]
path = 'contracts/glamora-nft.clar'
clarity_version = 3
epoch = 3.0
depends_on = ["storage", "sip-009"]

[contracts.main]
path = 'contracts/main.clar'
clarity_version = 3
epoch = 3.0
depends_on = ["sip-009", "storage", "glamora-nft", "sbtc-token"]

[contracts.sip-009]
path = 'contracts/sip-009.clar'
clarity_version = 3
epoch = 3.0

[contracts.storage]
path = 'contracts/storage.clar'
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
